# Generated by Django 4.2.6 on 2024-03-17 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=100)),
                ('air_conditioner', models.BooleanField(default=True)),
                ('name_model', models.CharField(max_length=100)),
                ('name_mark', models.CharField(max_length=100)),
                ('picture', models.URLField()),
                ('status', models.CharField(max_length=100)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('gallerie', models.JSONField(default=list)),
                ('portes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('localisation', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('is_airport', models.BooleanField(default=False)),
                ('description_city', models.TextField(blank=True, null=True)),
                ('picture_city', models.URLField(blank=True, null=True)),
                ('gallerie_city', models.JSONField(default=list)),
                ('destination_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.city')),
            ],
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_partner_company', models.CharField(max_length=100)),
                ('code_partner_company', models.CharField(max_length=100)),
                ('email_partner_company', models.EmailField(max_length=254)),
                ('phone_number_partner_company', models.CharField(max_length=100)),
                ('address_partner_company', models.CharField(max_length=255)),
                ('localisation_partner_company', models.CharField(blank=True, max_length=100, null=True)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TypeCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rentalcar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('price_rental', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_with_driver', models.DecimalField(decimal_places=2, max_digits=10)),
                ('with_driver', models.CharField(max_length=100)),
                ('price_repas_driver', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_hebergement_driver', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_chaise_bebe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reduction_pourcentage', models.IntegerField()),
                ('reduction_days', models.IntegerField()),
                ('limit_km', models.IntegerField()),
                ('price_extra_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_place', models.IntegerField()),
                ('caution', models.DecimalField(decimal_places=2, max_digits=10)),
                ('with_reduction', models.BooleanField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_location', to='api.car')),
                ('cities', models.ManyToManyField(related_name='location_cities', to='api.city')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_location', to='api.partenaire')),
            ],
        ),
        migrations.CreateModel(
            name='OutsideRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('package_one_way', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_entreprise', models.BooleanField(default=False)),
                ('chaise_bebe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('animal_compagnie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adress_supplementaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_pax', models.CharField(max_length=100)),
                ('number_luggage', models.CharField(max_length=100)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.car')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_from_city', to='api.city')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_to_city', to='api.city')),
            ],
        ),
        migrations.CreateModel(
            name='NavetteAeroport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('price_airport', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_airport_roundTrip', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_pax_airport', models.CharField(max_length=100)),
                ('number_luggage_airport', models.CharField(max_length=100)),
                ('chaise_bebe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('animal_compagnie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adress_supplementaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_entreprise', models.BooleanField(default=False)),
                ('enable', models.BooleanField(default=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.car')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_city', to='api.city')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_city', to='api.city')),
            ],
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('enable', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('medias_images', models.JSONField()),
                ('medias_video', models.URLField(blank=True, max_length=500)),
                ('serice_include', models.JSONField()),
                ('serice_exclus', models.JSONField()),
                ('type_coverture', models.JSONField()),
                ('disponibility', models.JSONField()),
                ('cities', models.ManyToManyField(to='api.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circuit_created_by', to=settings.AUTH_USER_MODEL)),
                ('disable_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circuit_disable_by', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.partenaire')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circuit_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.typecar'),
        ),
    ]
